<a href="https://colab.research.google.com/github/Romanzilla/ML/blob/main/%D0%9B%D0%A01_%D0%9C%D0%9D_%D0%9D%D0%B0%D0%B4%D1%96%D0%B9%D0%BA%D0%BE_%D0%B3%D1%80%D1%83%D0%BF%D0%B03_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [1]:
import numpy as np

print(np.__version__)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [2]:
arr = np.array([2, 4, 6, 8, 10])

print(arr)
print(type(arr))


[ 2  4  6  8 10]
<class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [3]:
zeros = np.zeros(10)
ones = np.ones(8)
sevens = np.full(6, 7)

print("Масив із 10 нулів:", zeros)
print("Масив із 8 одиниць:", ones)
print("Масив із 6 сімок:", sevens)


Масив із 10 нулів: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Масив із 8 одиниць: [1. 1. 1. 1. 1. 1. 1. 1.]
Масив із 6 сімок: [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [4]:
numbers = np.arange(1, 21)
even_numbers = np.arange(2, 21, 2)

print("Числа від 1 до 20:", numbers)
print("Парні числа:", even_numbers)


Числа від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні числа: [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [5]:
numbers = np.linspace(0, 1, 11)

print(numbers)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [6]:
numbers = np.arange(1, 13)
matrix = numbers.reshape(3, 4)

print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [7]:
print("Кількість вимірів:", matrix.ndim)
print("Форма:", matrix.shape)
print("Кількість елементів:", matrix.size)
print("Тип даних:", matrix.dtype)


Кількість вимірів: 2
Форма: (3, 4)
Кількість елементів: 12
Тип даних: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [8]:
arr = np.array([1.2, 3.5, 5.7, 7.9])

new_arr = arr.astype(int)

print(new_arr)


[1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший елемент:", arr[0])
print("Останній елемент:", arr[-1])
print("Елементи з індексами 2–5:", arr[2:6])
print("Кожен другий елемент:", arr[::2])


Перший елемент: 10
Останній елемент: 80
Елементи з індексами 2–5: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [10]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Елемент 7:", matrix[1, 2])
print("Другий рядок:", matrix[1])
print("Третій стовпець:", matrix[:, 2])
print("Підматриця:")
print(matrix[1:, :2])


Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця:
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [11]:
arr = np.arange(1, 16)

arr[5:10] = 0

print(arr)


[ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [12]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("Ділення:", a / b)


Додавання: [11 22 33 44 55]
Віднімання: [ -9 -18 -27 -36 -45]
Множення: [ 10  40  90 160 250]
Ділення: [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [13]:
arr = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr))
print("Середнє:", np.mean(arr))
print("Мінімум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Медіана:", np.median(arr))
print("Стандартне відхилення:", np.std(arr))

Сума: 108
Середнє: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [14]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Сума всіх елементів:", np.sum(matrix))
print("Сума по стовпцях:", np.sum(matrix, axis=0))
print("Сума по рядках:", np.sum(matrix, axis=1))
print("Середнє по стовпцях:", np.mean(matrix, axis=0))


Сума всіх елементів: 45
Сума по стовпцях: [12 15 18]
Сума по рядках: [ 6 15 24]
Середнє по стовпцях: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [15]:
arr = np.arange(1, 11)

print("Квадрати:", np.square(arr))
print("Квадратні корені:", np.sqrt(arr))
print("Натуральні логарифми:", np.log(arr))


Квадрати: [  1   4   9  16  25  36  49  64  81 100]
Квадратні корені: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральні логарифми: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [16]:
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Числа більші за 15:", arr[arr > 15])
print("Парні числа:", arr[arr % 2 == 0])
print("Числа від 10 до 30:", arr[(arr >= 10) & (arr <= 30)])


Числа більші за 15: [18 21 25 30 34]
Парні числа: [12 18 30 34]
Числа від 10 до 30: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [17]:
arr = np.array([-5, 3, -2, 8, -1, 10, 0])

arr[arr < 0] = 0

print(arr)


[ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [18]:
np.random.seed(42)

arr = np.random.randint(0, 101, 20)

print("Масив:", arr)
print("Кількість елементів > 50:", np.sum(arr > 50))
print("Кількість елементів <= 50:", np.sum(arr <= 50))


Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість елементів > 50: 12
Кількість елементів <= 50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [19]:
arr = np.arange(1, 25)

matrix_4x6 = arr.reshape(4, 6)
matrix_6x4 = arr.reshape(6, 4)
array_3d = arr.reshape(2, 3, 4)

print("Матриця 4 × 6:")
print(matrix_4x6)
print("shape:", matrix_4x6.shape)

print("\nМатриця 6 × 4:")
print(matrix_6x4)
print("shape:", matrix_6x4.shape)

print("\nТривимірний масив 2 × 3 × 4:")
print(array_3d)
print("shape:", array_3d.shape)


Матриця 4 × 6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
shape: (4, 6)

Матриця 6 × 4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
shape: (6, 4)

Тривимірний масив 2 × 3 × 4:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
shape: (2, 3, 4)


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [20]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

vertical = np.vstack((A, B))
horizontal = np.hstack((A, B))

print("Вертикальне об'єднання:")
print(vertical)

print("\nГоризонтальне об'єднання:")
print(horizontal)


Вертикальне об'єднання:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Горизонтальне об'єднання:
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [21]:
matrix = np.arange(1, 13).reshape(3, 4)

arr_flatten = matrix.flatten()
arr_ravel = matrix.ravel()

print("Початкова матриця:")
print(matrix)

print("\nflatten():", arr_flatten)
print("ravel():", arr_ravel)

print("\n Результати однакові:", np.array_equal(arr_flatten, arr_ravel))


Початкова матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

 Результати однакові: True


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [22]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("Сума:", a + b)
print("Різниця:", a - b)
print("a × 3:", a * 3)
print("b × 3:", b * 3)


Сума: [ 3  7 11]
Різниця: [1 1 1]
a × 3: [ 6 12 18]
b × 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_1 = np.dot(a, b)
dot_2 = a @ b

print("np.dot():", dot_1)
print("Оператор @:", dot_2)


np.dot(): 32
Оператор @: 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [24]:
v = np.array([3, 4])

norm = np.linalg.norm(v)
normalized = v / norm

print("Евклідова норма:", norm)
print("Нормалізований вектор:", normalized)
print("Норма нормалізованого вектора:", np.linalg.norm(normalized))


Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]
Норма нормалізованого вектора: 1.0


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [25]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

result = np.cross(a, b)

print("Векторний добуток:", result)


Векторний добуток: [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [26]:
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

angle = np.degrees(np.arccos(cos_angle))

print("Косинус кута:", cos_angle)
print("Кут у градусах:", angle)


Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

transpose_1 = A.T
transpose_2 = np.transpose(A)

print("За допомогою .T:")
print(transpose_1)

print("\nЗа допомогою np.transpose():")
print(transpose_2)


За допомогою .T:
[[1 4]
 [2 5]
 [3 6]]

За допомогою np.transpose():
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [28]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [2, 0],
    [1, 2]
])

print("Поелементний добуток A * B:")
print(A * B)

print("\nМатричний добуток A @ B:")
print(A @ B)

# A * B множить відповідні елементи матриць.
# A @ B виконує матричне множення.


Поелементний добуток A * B:
[[2 0]
 [3 8]]

Матричний добуток A @ B:
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [29]:
A = np.array([
    [4, 7],
    [2, 6]
])

det = np.linalg.det(A)
inverse = np.linalg.inv(A)

print("Визначник:", det)

print("\n Обернена матриця:")
print(inverse)

print("\n Перевірка A @ A⁻¹:")
print(A @ inverse)


Визначник: 10.000000000000002

 Обернена матриця:
[[ 0.6 -0.7]
 [-0.2  0.4]]

 Перевірка A @ A⁻¹:
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [30]:
A = np.array([
    [2, 1],
    [1, 3]
])

b = np.array([5, 6])

x = np.linalg.solve(A, b)

print("Розв'язок системи:")
print("x =", x[0])
print("y =", x[1])


Розв'язок системи:
x = 1.8
y = 1.4


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [31]:
I = np.eye(4)

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

result = A @ I

print("Одинична матриця:")
print(I)

print("\nПочаткова матриця:")
print(A)

print("\nРезультат A @ I:")
print(result)

print("\nРезультат дорівнює початковій:", np.array_equal(A, result))


Одинична матриця:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Початкова матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Результат A @ I:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Результат дорівнює початковій: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [32]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

result = A + 10

print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [33]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

v = np.array([10, 20, 30])

result = A + v

print(result)

# Вектор v додається до кожного рядка матриці A.
# NumPy автоматично застосовує broadcasting.


[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [34]:
A = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

mean = np.mean(A, axis=0)
std = np.std(A, axis=0)

Z = (A - mean) / std

print("Середні значення стовпців:", mean)
print("Стандартні відхилення:", std)

print("\nНормалізована матриця:")
print(Z)


Середні значення стовпців: [20. 30. 40.]
Стандартні відхилення: [8.16496581 8.16496581 8.16496581]

Нормалізована матриця:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [35]:
np.random.seed(42)

# 1. 10 випадкових цілих чисел від 1 до 100
numbers = np.random.randint(1, 101, 10)

# 2. Матриця 3 × 3 випадкових чисел від 0 до 1
matrix = np.random.rand(3, 3)

# 3. 1000 значень із нормального розподілу
normal_data = np.random.normal(size=1000)

print("10 випадкових чисел:")
print(numbers)

print("\nМатриця 3 × 3:")
print(matrix)

print("\nСереднє нормального розподілу:", np.mean(normal_data))
print("Стандартне відхилення:", np.std(normal_data))


10 випадкових чисел:
[52 93 15 72 61 21 83 87 75 75]

Матриця 3 × 3:
[[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]

Середнє нормального розподілу: 0.02216865975826456
Стандартне відхилення: 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [36]:
np.random.seed(42)

grades = np.random.randint(0, 101, 30)

print("Оцінки:", grades)
print("Середня оцінка:", np.mean(grades))
print("Медіана:", np.median(grades))
print("Найвища оцінка:", np.max(grades))
print("Найнижча оцінка:", np.min(grades))
print("Кількість оцінок >= 60:", np.sum(grades >= 60))

percent_90 = np.sum(grades >= 90) / len(grades) * 100
print("Відсоток оцінок >= 90:", percent_90, "%")

Оцінки: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
Середня оцінка: 50.86666666666667
Медіана: 54.5
Найвища оцінка: 99
Найнижча оцінка: 1
Кількість оцінок >= 60: 13
Відсоток оцінок >= 90: 6.666666666666667 %


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [37]:
sales = np.array([
    [120, 150, 170, 160],
    [80, 90, 100, 110],
    [200, 180, 210, 230]
])

# 1. Загальний обсяг продажів кожного товару
product_sales = np.sum(sales, axis=1)

# 2. Загальний обсяг продажів у кожному місяці
monthly_sales = np.sum(sales, axis=0)

# 3. Товар із найбільшими продажами
best_product = np.argmax(product_sales) + 1

# 4. Місяць із найбільшими продажами
best_month = np.argmax(monthly_sales) + 1

# 5. Середній обсяг продажів кожного товару
average_sales = np.mean(sales, axis=1)

print("Продажі кожного товару:", product_sales)
print("Продажі кожного місяця:", monthly_sales)
print("Товар із найбільшими продажами: №", best_product)
print("Місяць із найбільшими продажами: №", best_month)
print("Середні продажі кожного товару:", average_sales)

Продажі кожного товару: [600 380 820]
Продажі кожного місяця: [400 420 480 500]
Товар із найбільшими продажами: № 3
Місяць із найбільшими продажами: № 4
Середні продажі кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [38]:
np.random.seed(42)

A = np.random.randint(1, 21, (5, 5))

print("Початкова матриця:")
print(A)

# 1. Сума головної діагоналі
main_diagonal_sum = np.trace(A)

# 2. Сума побічної діагоналі
secondary_diagonal_sum = np.trace(np.fliplr(A))

# 3. Максимальний елемент кожного рядка
row_max = np.max(A, axis=1)

# 4. Мінімальний елемент кожного стовпця
column_min = np.min(A, axis=0)

# 5. Заміна елементів, менших за середнє, на 0
mean_value = np.mean(A)
result = A.copy()
result[result < mean_value] = 0

print("\nСума головної діагоналі:", main_diagonal_sum)
print("Сума побічної діагоналі:", secondary_diagonal_sum)
print("Максимум кожного рядка:", row_max)
print("Мінімум кожного стовпця:", column_min)
print("Середнє значення:", mean_value)

print("\nМатриця після заміни:")
print(result)


Початкова матриця:
[[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]

Сума головної діагоналі: 59
Сума побічної діагоналі: 32
Максимум кожного рядка: [20 19 12 17 19]
Мінімум кожного стовпця: [ 2  1  2 11  4]
Середнє значення: 10.52

Матриця після заміни:
[[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [39]:
X = np.array([
    [2, 4, 6],
    [1, 3, 5],
    [5, 7, 9]
])

distance_12 = np.linalg.norm(X[0] - X[1])
distance_13 = np.linalg.norm(X[0] - X[2])
distance_23 = np.linalg.norm(X[1] - X[2])

print("Відстань між 1 і 2 рядками:", distance_12)
print("Відстань між 1 і 3 рядками:", distance_13)
print("Відстань між 2 і 3 рядками:", distance_23)


Відстань між 1 і 2 рядками: 1.7320508075688772
Відстань між 1 і 3 рядками: 5.196152422706632
Відстань між 2 і 3 рядками: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [40]:
np.random.seed(42)

A = np.random.randint(1, 21, (4, 4))

# Норми кожного рядка
norms = np.linalg.norm(A, axis=1)

# Нормалізація кожного рядка
normalized = A / norms[:, np.newaxis]

print("Початкова матриця:")
print(A)

print("\nНорми рядків:")
print(norms)

print("\nНормалізована матриця:")
print(normalized)


Початкова матриця:
[[ 7 20 15 11]
 [ 8  7 19 11]
 [11  4  8  3]
 [ 2 12  6  2]]

Норми рядків:
[28.19574436 24.39262184 14.49137675 13.7113092 ]

Нормалізована матриця:
[[0.24826442 0.7093269  0.53199518 0.3901298 ]
 [0.32796802 0.28697202 0.77892406 0.45095603]
 [0.75907212 0.27602622 0.55205245 0.20701967]
 [0.14586499 0.87518995 0.43759497 0.14586499]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [41]:
A = np.array([
    [1, 2, 1],
    [2, 1, -1],
    [3, -1, 2]
])

b = np.array([9, 8, 3])

# 1. Розв'язання системи
x = np.linalg.solve(A, b)

print("Розв'язок системи:")
print(x)

# 2. Перевірка A @ x
result = A @ x

print("\nA @ x:")
print(result)

# 3. Порівняння з b
print("\nВектор b:")
print(b)

print("\nЧи дорівнює A @ x вектору b:")
print(np.allclose(result, b))


Розв'язок системи:
[ 2.22222222  3.44444444 -0.11111111]

A @ x:
[9. 8. 3.]

Вектор b:
[9 8 3]

Чи дорівнює A @ x вектору b:
True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
